name: Publish extension

on:
  push:
    tags:
      - 'v*'

jobs:
  build-publish-extension:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Run lint
      run: npm run lint
    - name: Build extension
      run: |
        mkdir dist
        cd ./extension
        zip -r ../dist/extension.zip *
        cd ..
    - name: Upload extension
      uses: mnao305/chrome-extension-upload@1.1.1
      with:
        file-path: dist/extension.zip
        extension-id: lmjcoecpdenpmdoieiiendpoohgmabmd
        client-id: ${{ secrets.CHROME_WEBSTORE_CLIENT_ID }}
        client-secret: ${{ secrets.CHROME_WEBSTORE_CLIENT_SECRET }}
        refresh-token: ${{ secrets.CHROME_WEBSTORE_REFRESH_TOKEN }}
