name: Publish extension

on:
  push:
    tags:
      - 'v*'

jobs:
  build-publish-extension-chrome:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Run lint
      run: npm run lint
    - name: Build extension
      run: |
        mkdir dist
        cd ./extension
        zip -r ../dist/extension.zip *
        cd ..
    - name: Upload extension
      uses: mnao305/chrome-extension-upload@1.1.1
      with:
        file-path: dist/extension.zip
        extension-id: lmjcoecpdenpmdoieiiendpoohgmabmd
        client-id: ${{ secrets.CHROME_WEBSTORE_CLIENT_ID }}
        client-secret: ${{ secrets.CHROME_WEBSTORE_CLIENT_SECRET }}
        refresh-token: ${{ secrets.CHROME_WEBSTORE_REFRESH_TOKEN }}
  build-release-extension-firefox:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Install web-ext
      run: |
        sudo npm install --global web-ext
    - name: Build binary package
      run: |
        npm install
        cd extension
        web-ext build
    - name: Upload binary package to Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: extension/web-ext-artifacts/*.zip
        overwrite: true
        file_glob: true
        tag: ${{ github.ref }}
